# =========================
# GENERAL OPTIONS
# =========================
dataset_cerra: "/projects/0/prjs1154/CentralEurope_2014_2020/CERRA"
dataset_era5: "/projects/0/prjs1154/CentralEurope_2014_2020/ERA5"
savepreds_path: null #"/projects/0/prjs1154/CentralEurope_2014_2020/preds_20142020_1dFFT"
model: Diffusion                   # Model architecture
subset_ds: 0                       # 0 = full dataset, >0 = subset size
seed: 42
n_workers: 8                       # Dataloader workers
load: saved_models/CorrDiffusion-0-Diffusion-06_24_17-8376/min_val_loss.ckpt
restore_opt: 0                     # 0 = do not restore optimizer
precision: "16-mixed"              # 32 | 16 | 16-mixed | bf16
eval: test                         # val | test | null → train
wandb_project: null #Diffusion-step #UNet-Cnn               # Optional wandb project name
run_name: CorrDiffusion-Inference        # Optional run name

# =========================
# DATASET SETTINGS
# =========================
output_variables: null             # List of vars to predict
img_in_channels: 15
img_out_channels: 5
img_resolution: [368, 368]

# =========================
# MODEL SETTINGS
# =========================
N_grid_channels: 4
embedding_type: zero
model_channels: 64
channel_mult: [1, 2, 2]
attn_resolutions: [16]
model_type: SongUNetPosEmbd
regression_net: saved_models/UNet-CNN-0-UNet-CNN-06_17_15-9228/min_val_loss.ckpt
gridtype: sinusoidal
hr_mean_conditioning: True

# =========================
# TRAINING SETTINGS
# =========================
val_interval: 1
lr: 2.0e-4
epochs: 1000
batch_size: 1
lr_decay: 1
lr_rampup: 0
grad_clip_threshold: null          # Set a number to enable clipping
checkpoint_level: 0

# =========================
# INFERENCE SETTINGS
# =========================
num_ensembles: 16