# =========================
# GENERAL OPTIONS
# =========================
dataset_cerra: "/projects/0/prjs0951/Carlo/zz_processed_data/CERRA"
dataset_era5: "/projects/0/prjs0951/Carlo/zz_processed_data/ERA5"
model: Swin-Unetr                  # Model architecture
subset_ds: 0                       # 0 = full dataset, >0 = subset size
seed: 32
n_workers: 32                       # Dataloader workers
load: null                          # No checkpoint loading - train from scratch
resume: null
restore_opt: 1                     # 0 = do not restore optimizer
precision: "16-mixed"              # 32 | 16 | 16-mixed | bf16
eval: null                         # val | test | null → train
wandb_project: finetune                #UNet-Cnn               # Optional wandb project name
run_name: Swin-FromScratch               # Optional run name

# =========================
# DATASET SETTINGS
# =========================
output_variables: null             # List of vars to predict
img_in_channels: 11
img_out_channels: 6
img_resolution: [384, 384]

# =========================
# MASKING SETTINGS
# =========================
mask_ratio: null                     # Ratio of input to mask
model_patch_size: 2
mask_patch_size: 32
use_light_decoder: False

# =========================
# MODEL SETTINGS
# =========================
embedding_type: zero
model_channels: 96
channel_mult: [1, 2, 2]
attn_resolutions: [16]
model_type: SwinUNETR
# freeze_encoder not needed - no checkpoint loaded (Experiment 3)

# =========================
# TRAINING SETTINGS
# =========================
val_interval: 1
lr: 2.0e-4
epochs: 300
batch_size: 64
lr_decay: 1
lr_rampup: 0
grad_clip_threshold: null          # Set a number to enable clipping
checkpoint_level: 0

