# =========================
# GENERAL OPTIONS
# =========================
dataset_cerra: "/projects/0/prjs1154/Iberia/CERRA"
dataset_era5: "/projects/0/prjs1154/Iberia/ERA5"
savepreds_path: "/projects/0/prjs1154/Iberia/preds"
graph:         "graph_UNet_midSize"
run_name:      "GNN-Unet"

# ------------------------------------------------------------------
#  Experiment logistics
# ------------------------------------------------------------------
batch_size:    2
epochs:        200
n_workers:     8
precision:     "16-mixed"
seed:          42
subset_ds:     1
val_interval:  1
wandb_project: null     # e.g. "neural-lam-HighLowRes-fix"

# ------------------------------------------------------------------
#  Checkpoint / restart
# ------------------------------------------------------------------
load:         "saved_models/UNet-GNN-BigData-graph_efm-4x64-05_22_10-8678/min_val_loss.ckpt"
restore_opt:  0         # 1 = also restore optimiser state

# ------------------------------------------------------------------
#  Model definition
# ------------------------------------------------------------------
model:                   "graph_efm"
variational:             False
# — sizes —
hidden_dim:              64
latent_dim:              null
hidden_layers:           1
processor_layers:        4
encoder_processor_layers: 2
prior_processor_layers:   2
# — graph options —
mesh_aggr:               "sum"
vertical_propnets:       0
# — probabilistic bits —
learn_prior:             1
output_std:              0
prior_dist:              "isotropic"

# ------------------------------------------------------------------
#  Optimisation & loss
# ------------------------------------------------------------------
kl_beta:      0.01
kl_term:      1
loss:         "mse"
lr:           0.001
step_length:  3          # forecasting horizon

# ------------------------------------------------------------------
#  Evaluation
# ------------------------------------------------------------------
eval: test
